unstable_features = true
edition = "2021"
fn_single_line = true
blank_lines_upper_bound = 1
fn_args_layout = "Compressed"
hard_tabs = true
format_generated_files = false
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
trailing_semicolon = false
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
wrap_comments = true
max_width = 120
comment_width = 120